/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Flashcard = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const Subject = IDL.Record({ 'name' : IDL.Text, 'studyTime' : IDL.Nat });

export const idlService = IDL.Service({
  'addExam' : IDL.Func([IDL.Text, IDL.Int], [IDL.Nat], []),
  'addNote' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addSubject' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createFlashcard' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
  'getDailyTimetable' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getDaysUntilExam' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Int)], ['query']),
  'getFlashcard' : IDL.Func([IDL.Nat], [Flashcard], ['query']),
  'removeSubject' : IDL.Func([IDL.Text], [], []),
  'updateFlashcard' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Flashcard = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const Subject = IDL.Record({ 'name' : IDL.Text, 'studyTime' : IDL.Nat });
  
  return IDL.Service({
    'addExam' : IDL.Func([IDL.Text, IDL.Int], [IDL.Nat], []),
    'addNote' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addSubject' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createFlashcard' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
    'getDailyTimetable' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getDaysUntilExam' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Int)], ['query']),
    'getFlashcard' : IDL.Func([IDL.Nat], [Flashcard], ['query']),
    'removeSubject' : IDL.Func([IDL.Text], [], []),
    'updateFlashcard' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };