/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Flashcard {
  'id' : bigint,
  'question' : string,
  'answer' : string,
}
export interface Subject { 'name' : string, 'studyTime' : bigint }
export interface _SERVICE {
  'addExam' : ActorMethod<[string, bigint], bigint>,
  'addNote' : ActorMethod<[string, string], bigint>,
  'addSubject' : ActorMethod<[string, bigint], undefined>,
  'createFlashcard' : ActorMethod<[string, string], bigint>,
  'getAllFlashcards' : ActorMethod<[], Array<Flashcard>>,
  'getDailyTimetable' : ActorMethod<[], Array<Subject>>,
  'getDaysUntilExam' : ActorMethod<[bigint], [] | [bigint]>,
  'getFlashcard' : ActorMethod<[bigint], Flashcard>,
  'removeSubject' : ActorMethod<[string], undefined>,
  'updateFlashcard' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];